export const ARTICLE_SEARCH_API = "https://api.nytimes.com/svc/search/v2/articlesearch.json"
export const BASE_MEDIA = "https://www.nytimes.com"
export const API_KEY = "Gv399IJT6eO5FtXGJcN6twMRipRYSAUj" // Ideally, this was wrapped in the backend.
export const TYPES_OF_MATERIALS = [
  "Addendum",
  "An Analysis",
  "An Appraisal",
  "Article",
  "Banner",
  "Biography",
  "Birth Notice",
  "Blog",
  "Brief",
  "Caption",
  "Chronology",
  "Column",
  "Correction",
  "Economic Analysis",
  "Editorial",
  "Editorial Cartoon",
  "Editors' Note",
  "First Chapter",
  "Front Page",
  "Glossary",
  "Interactive Feature",
  "Interactive Graphic",
  "Interview",
  "Letter",
  "List",
  "Marriage Announcement",
  "Military Analysis",
  "News",
  "News Analysis",
  "Newsletter",
  "Obituary",
  "Obituary (Obit)",
  "Op-Ed",
  "Paid Death Notice",
  "Postscript",
  "Premium",
  "Question",
  "Quote",
  "Recipe",
  "Review",
  "Schedule",
  "SectionFront",
  "Series",
  "Slideshow",
  "Special Report",
  "Statistics",
  "Summary",
  "Text",
  "Video",
  "Web Log"
]